### ISSUE TITLE
[Weekly Digest] Apr 6, 2020 - Apr 12, 2020

### ISSUE THREAD

**Issue by ghost** [ArkEcosystem/typescript-peers#48]
Here's the **Weekly Digest** from **Mon, Apr 6, 2020 12:00 AM** to **Sun, Apr 12, 2020 11:59 PM** for [*ArkEcosystem/typescript-peers*](https://github.com/ArkEcosystem/typescript-peers).

## Issues

Last week there were no issues.

## Pull Requests

Last week, no pull-requests were opened, closed or merged.

## Releases

Last week there were no releases.

## Contributors

Last week there were no contributors.

## Star Gazers

Last week there was 1 stargazer.

@Huynhhung0

You are the star! :star2:

-----

That's all activities since Mon, Apr 6, 2020 12:00 AM, please _**Watch**_ and _**Star**_ the repository [*ArkEcosystem/typescript-peers*](https://github.com/ArkEcosystem/typescript-peers) to receive upcoming weekly updates.

**You can also [view all Weekly Digests by clicking here](https://github.com/ArkEcosystem/typescript-peers/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Weekly+Digest%22).**

**Comment by Huynhhung0** [comment]
thank you very much !!! <3
